import type { Metadata } from 'next';
import { Nunito } from 'next/font/google';
import './globals.css';
import { Footer, Header } from '@/components';

export const nunito = Nunito({
  variable: '--font-nunito',
  weight: ['400', '500', '600', '700'],
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      {/* TODO: Criar um componente layout que irá receber uma prop se deve ou não mostrar o search */}
      <body className={`${nunito.variable} font-nunito antialiased`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
